apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 1m0s
  url: YOUR_GIT_REPO_URL
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  timeout: 2m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 5m0s
  path: ./istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  dependsOn:
    - name: istio
  interval: 5m0s
  path: ./observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: observability
  interval: 5m0s
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  timeout: 10m0s
