apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
# ServiceAccount and RBAC are managed by the Helm chart below

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 10m0s
  chart:
    spec:
      chart: headlamp
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    serviceAccount:
      create: true
      name: headlamp-admin
    rbac:
      create: true
      clusterRoleBinding:
        create: true
    ingress:
      enabled: false
    service:
      type: ClusterIP
    config:
      pluginsDir: /build/plugins
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: headlamp
  namespace: headlamp
spec:
  hosts:
    - headlamp.${INGRESS_IP}.sslip.io
  gateways:
    - istio-system/default-gateway
  http:
    - route:
        - destination:
            host: headlamp.headlamp.svc.cluster.local
            port:
              number: 80


