---
- name: Install k3s cluster
  hosts: all
  become: true

  roles:
    - role: xanmanning.k3s

  post_tasks:
    - name: Show kubeconfig path on master
      ansible.builtin.debug:
        msg: "/etc/rancher/k3s/k3s.yaml contains the kubeconfig on the master node"
      when: inventory_hostname in groups['master']

