apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: true
      adminPassword: admin
      podAnnotations:
        proxy.istio.io/config: |
          tracing: {}
      service:
        type: ClusterIP
      # Istio Grafana dashboards
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'istio'
              orgId: 1
              folder: 'Istio'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/istio
      dashboards:
        istio:
          istio-mesh:
            gnetId: 7639
            revision: 173
            datasource: Prometheus
          istio-service:
            gnetId: 7636
            revision: 173
            datasource: Prometheus
          istio-workload:
            gnetId: 7630
            revision: 173
            datasource: Prometheus
          istio-control-plane:
            gnetId: 7645
            revision: 173
            datasource: Prometheus
          istio-performance:
            gnetId: 11829
            revision: 173
            datasource: Prometheus
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        # Additional scrape configs for Istio
        additionalScrapeConfigs:
          - job_name: 'istiod'
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring
          - job_name: 'envoy-stats'
            metrics_path: /stats/prometheus
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: observability
spec:
  interval: 10m0s
  chart:
    spec:
      chart: loki-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      isDefault: true
    promtail:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  interval: 10m0s
  chart:
    spec:
      chart: jaeger
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
    storage:
      type: memory
    allInOne:
      enabled: true
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
