apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: v1
kind: Secret
metadata:
  name: runner-registration
  namespace: gitlab
type: Opaque
stringData:
  runner-registration-token: "" # need to leave as an empty string for compatibility reasons
  runner-token: "glrtr-m-kR_yjLTEwbzNsGHtQT"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
stringData:
  config: |
    filesystem:
      rootdirectory: /var/opt/gitlab/gitlab-rails/shared/registry
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 20m0s
  chart:
    spec:
      chart: gitlab
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: ${INGRESS_IP}.sslip.io
        https: false
        gitlab:
          name: gitlab.${INGRESS_IP}.sslip.io
        registry:
          name: registry.${INGRESS_IP}.sslip.io
      ingress:
        enabled: false
        configureCertmanager: false
      kas:
        enabled: false
      appConfig:
        enableUsagePing: false
      registry:
        api:
          url: http://gitlab-registry.gitlab.svc.cluster.local:5000
      psql:
        image:
          tag: 15
      storage:
        class: longhorn
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    registry:
      enabled: true
      hpa:
        minReplicas: 1
      storage:
        secret: gitlab-registry-storage
        key: config
    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
        hpa:
          minReplicas: 1
    gitlab-runner:
      install: false
    redis:
      master:
        persistence:
          storageClass: longhorn
      replica:
        persistence:
          storageClass: longhorn
    postgresql:
      primary:
        persistence:
          storageClass: longhorn
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 10m0s
  chart:
    spec:
      chart: gitlab-runner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    replicas: 1
    gitlabUrl: "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181"
    # TODO needs to be automatically done via ansible
    runnerToken: "glrtr-m-kR_yjLTEwbzNsGHtQT"
    unregisterRunners: false
    rbac:
      create: true
    runners:
      privileged: true
      image: ubuntu:22.04
      config: |
        [[runners]]
          clone_url = "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181"

          environment = [
            "CI_REGISTRY=gitlab-registry.gitlab.svc.cluster.local:5000",
            "CI_SERVER_HOST=gitlab-webservice-default.gitlab.svc.cluster.local",
            "CI_SERVER_PORT=8181",
            "CI_SERVER_PROTOCOL=http",
            "DOCKER_TLS_CERTDIR="
          ]
          pre_build_script = """
            # Override any registry variables that might use external hostnames
            export CI_REGISTRY="gitlab-registry.gitlab.svc.cluster.local:5000"
            export CI_REGISTRY_IMAGE="$$CI_REGISTRY/$$CI_PROJECT_PATH"
            
            # Configure Docker to allow insecure registries (HTTP without TLS)
            mkdir -p /etc/docker
            cat > /etc/docker/daemon.json <<EOF
{
  "insecure-registries": [
    "gitlab-registry.gitlab.svc.cluster.local:5000",
    "registry.gitlab.svc.cluster.local:5000",
    "registry.${INGRESS_IP}.sslip.io"
  ]
}
EOF
            
            echo "Using internal registry: $$CI_REGISTRY"
            echo "Registry image: $$CI_REGISTRY_IMAGE"
            echo "Configured insecure registries for HTTP access"
          """
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:22.04"
            privileged = true
            [[runners.kubernetes.host_aliases]]
              ip = "10.43.37.72"
              hostnames = ["registry.${INGRESS_IP}.sslip.io"]
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab
  namespace: gitlab
spec:
  hosts:
    - gitlab.${INGRESS_IP}.sslip.io
  gateways:
    - istio-system/default-gateway
  http:
    - route:
        - destination:
            host: gitlab-webservice-default.gitlab.svc.cluster.local
            port:
              number: 8181
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  hosts:
    - registry.${INGRESS_IP}.sslip.io
  gateways:
    - istio-system/default-gateway
  http:
    - route:
        - destination:
            host: gitlab-registry.gitlab.svc.cluster.local
            port:
              number: 5000
