apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: v1
kind: Secret
metadata:
  name: runner-registration
  namespace: gitlab
stringData:
  runner-token: "glrtr-m-kR_yjLTEwbzNsGHtQT"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 20m0s
  chart:
    spec:
      chart: gitlab
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: ${INGRESS_IP}.sslip.io
        https: false
        gitlab:
          name: gitlab.${INGRESS_IP}.sslip.io
        registry:
          name: registry.${INGRESS_IP}.sslip.io
      ingress:
        enabled: false
        configureCertmanager: false
      kas:
        enabled: false
      appConfig:
        enableUsagePing: false
      psql:
        image:
          tag: 15
      storage:
        class: longhorn
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    registry:
      enabled: true
      hpa:
        minReplicas: 1
      storage:
        secret:
          s3:
            accesskey: ""
            secretkey: ""
        filesystem:
          enabled: true
    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
        hpa:
          minReplicas: 1
    gitlab-runner:
      install: false
    redis:
      master:
        persistence:
          storageClass: longhorn
      replica:
        persistence:
          storageClass: longhorn
    postgresql:
      primary:
        persistence:
          storageClass: longhorn
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 10m0s
  chart:
    spec:
      chart: gitlab-runner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    replicas: 1
    gitlabUrl: "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181"
    unregisterRunners: true
    runners:
      privileged: true
      image: ubuntu:22.04
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
    secret: runner-registration
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab
  namespace: gitlab
spec:
  hosts:
    - gitlab.${INGRESS_IP}.sslip.io
  gateways:
    - istio-system/default-gateway
  http:
    - route:
        - destination:
            host: gitlab-webservice-default.gitlab.svc.cluster.local
            port:
              number: 8181
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  hosts:
    - registry.${INGRESS_IP}.sslip.io
  gateways:
    - istio-system/default-gateway
  http:
    - route:
        - destination:
            host: registry.gitlab.svc.cluster.local
            port:
              number: 5000
