---
- name: Migrate Flux to In-Cluster GitLab
  ansible.builtin.import_playbook: ../includes/setup-gitlab-project.yml

- name: Setup Flux Authentication
  ansible.builtin.import_playbook: ../includes/setup-flux-auth.yml

- name: Setup GitLab Runner Authentication
  ansible.builtin.import_playbook: ../includes/setup-gitlab-runner.yml

- name: Display Migration Summary
  hosts: localhost
  become: false
  connection: local
  gather_facts: false

  vars:
    gitlab_host: "gitlab.{{ ingress_ip }}.sslip.io"
    gitlab_url: "https://{{ gitlab_host }}"
    gitlab_internal_host: "gitlab-webservice-default.gitlab.svc.cluster.local:8181"
    gitlab_project_namespace: "infrastructure"
    gitlab_project_name: "cluster-config"
    gitlab_project_path: "{{ gitlab_project_namespace }}/{{ gitlab_project_name }}"

  tasks:
    - name: Display final summary
      ansible.builtin.debug:
        msg:
          - "======================================================================"
          - "Migration to In-Cluster GitLab Complete!"
          - "======================================================================"
          - ""
          - "GitLab Project: {{ gitlab_url }}/{{ gitlab_project_path }}"
          - ""
          - "External URL (for git operations from outside cluster):"
          - "  Use: git push incluster main"
          - ""
          - "Internal URL (for Flux inside cluster):"
          - "  http://{{ gitlab_internal_host }}/{{ gitlab_project_path }}.git"
          - ""
          - "Authentication:"
          - "  Flux uses deploy token via Secret 'gitlab-auth' in namespace 'flux-system'"
          - ""
          - "GitLab Runner:"
          - "  ✓ Runner authentication token configured"
          - "  ✓ Runner configured automatically in HelmRelease"
          - "  Check status: kubectl get pods -n gitlab -l app=gitlab-runner"
          - ""
          - "You can now:"
          - "  1. Push changes: git push incluster main"
          - "  2. Flux will automatically sync from in-cluster GitLab"
          - "  3. GitLab Runner is ready to execute CI/CD pipelines"
          - ""
          - "To use the in-cluster GitLab as origin:"
          - "  git remote set-url origin $(git remote get-url incluster)"
          - "======================================================================"
