---
- name: Restart k3s cluster
  hosts: all
  become: true
  
  tasks:
    # First, restart workers gracefully
    - name: Restart k3s-agent on worker nodes
      ansible.builtin.systemd:
        name: k3s-agent
        state: restarted
        enabled: true
      when: inventory_hostname in groups['workers'] | default([])
      register: worker_restart

    - name: Wait for worker restart to complete
      ansible.builtin.pause:
        seconds: 15
      when: inventory_hostname in groups['workers'] | default([])

    # Then restart master nodes
    - name: Restart k3s service on master nodes
      ansible.builtin.systemd:
        name: k3s
        state: restarted
        enabled: true
      when: inventory_hostname in groups['master']
      register: master_restart

    - name: Wait for k3s to be ready on master after restart
      ansible.builtin.wait_for:
        port: 6443
        delay: 5
        timeout: 300
      when: inventory_hostname in groups['master']

    - name: Verify k3s API is responding after restart
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:6443/healthz"
        validate_certs: false
        status_code: 200
      retries: 30
      delay: 2
      register: api_health
      until: api_health.status == 200
      when: inventory_hostname in groups['master']

    - name: Wait for all nodes to stabilize
      ansible.builtin.pause:
        seconds: 20
      run_once: true

    - name: Show restart status
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} k3s services restarted successfully"

  post_tasks:
    - name: Wait for cluster to be fully ready
      ansible.builtin.pause:
        seconds: 10
      run_once: true

    - name: Display cluster status on master
      ansible.builtin.shell: kubectl get nodes
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: cluster_status
      changed_when: false
      when: inventory_hostname in groups['master']

    - name: Show cluster nodes
      ansible.builtin.debug:
        var: cluster_status.stdout_lines
      when: inventory_hostname in groups['master'] and cluster_status.stdout_lines is defined

    - name: Check pod status
      ansible.builtin.shell: kubectl get pods --all-namespaces
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: pod_status
      changed_when: false
      when: inventory_hostname in groups['master']

    - name: Show pod status
      ansible.builtin.debug:
        var: pod_status.stdout_lines
      when: inventory_hostname in groups['master'] and pod_status.stdout_lines is defined

