# Wildcard certificate for all services using sslip.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-sslip-cert
  namespace: istio-system
spec:
  secretName: wildcard-sslip-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  commonName: "*.sslip.io"
  dnsNames:
    - "*.${INGRESS_IP}.sslip.io"
    - "${INGRESS_IP}.sslip.io"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

