---
- name: Setup local kubeconfig
  hosts: master
  become: true

  tasks:
    - name: Fetch kubeconfig from master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/tmp/k3s.yaml"
        flat: true
      run_once: true

    - name: Rewrite server address in fetched kubeconfig to master IP
      ansible.builtin.replace:
        path: /tmp/k3s.yaml
        regexp: 'server: https://127\.0\.0\.1:6443'
        replace: "server: https://{{ hostvars[groups['master'][0]].ansible_host }}:6443"
      become: false
      delegate_to: localhost
      run_once: true

    - name: Ensure local ~/.kube directory exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') + '/.kube' }}"
        state: directory
        mode: "0700"
      become: false
      delegate_to: localhost
      run_once: true

    - name: Initialize local kubeconfig if missing
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'HOME') + '/.kube/config' }}"
        content: ""
        mode: "0600"
        force: no
      become: false
      delegate_to: localhost
      run_once: true

    - name: Backup existing local kubeconfig
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') + '/.kube/config' }}"
        dest: "{{ lookup('env', 'HOME') + '/.kube/config.bak' }}"
        mode: "0600"
        remote_src: true
      become: false
      delegate_to: localhost
      run_once: true

    - name: Merge k3s kubeconfig into local kubeconfig
      ansible.builtin.shell: |
        set -euo pipefail
        KUBECONFIG="{{ lookup('env', 'HOME') + '/.kube/config' }}:/tmp/k3s.yaml" kubectl config view --flatten > "{{ lookup('env', 'HOME') + '/.kube/config.new' }}"
        mv "{{ lookup('env', 'HOME') + '/.kube/config.new' }}" "{{ lookup('env', 'HOME') + '/.kube/config' }}"
      args:
        executable: /bin/bash
      become: false
      delegate_to: localhost
      run_once: true

